# Generated by Django 3.1.4 on 2021-01-02 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('visitor_allowed', models.BooleanField(default=False)),
                ('planned_service_date', models.DateTimeField(null=True)),
                ('last_service_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=10)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=25)),
                ('countrycd', models.CharField(max_length=4)),
                ('emergency_available', models.BooleanField(default=True)),
                ('has_lab', models.BooleanField(default=True)),
                ('provides_ambulance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15)),
                ('tollfree_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=15)),
                ('required_experience', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('closure_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_open', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.departmentinformation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.hospitalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=4)),
                ('block', models.CharField(max_length=20)),
                ('sub_block', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.departmentinformation')),
            ],
        ),
        migrations.AddIndex(
            model_name='hospitalinformation',
            index=models.Index(fields=['name'], name='hospital_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalinformation',
            index=models.Index(fields=['city', 'region', 'country'], name='location_idx'),
        ),
        migrations.AddField(
            model_name='departmentinformation',
            name='depart_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentinformation',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.hospitalinformation'),
        ),
        migrations.AddField(
            model_name='bedinformation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.roominformation'),
        ),
        migrations.AddIndex(
            model_name='vacancyinfo',
            index=models.Index(fields=['type', 'position', 'department'], name='vacantpost_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancyinfo',
            index=models.Index(fields=['closure_date'], name='closedt_idx'),
        ),
        migrations.AddIndex(
            model_name='roominformation',
            index=models.Index(fields=['is_active', 'room_type'], name='roomty_idx'),
        ),
        migrations.AddIndex(
            model_name='bedinformation',
            index=models.Index(fields=['is_active', 'is_occupied'], name='available_idx'),
        ),
        migrations.AddIndex(
            model_name='bedinformation',
            index=models.Index(fields=['planned_service_date'], name='service_idx'),
        ),
    ]
