# Generated by Django 3.1.4 on 2021-01-27 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalinformation',
            name='countrycd',
        ),
        migrations.AddField(
            model_name='hospitalinformation',
            name='website',
            field=models.CharField(help_text='Website Link', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancyinfo',
            name='link',
            field=models.CharField(help_text='Application Link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='bed_type',
            field=models.CharField(help_text='Bed Type', max_length=4),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='is_occupied',
            field=models.BooleanField(default=False, help_text='Occupied/Vacant'),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='last_service_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Last service Date'),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='planned_service_date',
            field=models.DateTimeField(help_text='Regular Planned Service Date', null=True),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='room',
            field=models.ForeignKey(help_text='Room Related To', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.roominformation'),
        ),
        migrations.AlterField(
            model_name='bedinformation',
            name='visitor_allowed',
            field=models.BooleanField(default=False, help_text='Visitor Allowed'),
        ),
        migrations.AlterField(
            model_name='departmentinformation',
            name='depart_head',
            field=models.ForeignKey(help_text='Department Name', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentinformation',
            name='hospital',
            field=models.ForeignKey(help_text='Related Hospital', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.hospitalinformation'),
        ),
        migrations.AlterField(
            model_name='departmentinformation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Closed/Serving'),
        ),
        migrations.AlterField(
            model_name='departmentinformation',
            name='name',
            field=models.CharField(help_text='Department Name', max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='address',
            field=models.CharField(help_text='Location', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='city',
            field=models.CharField(help_text='City', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='country',
            field=models.CharField(help_text='Country', max_length=25),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='emergency_available',
            field=models.BooleanField(default=True, help_text='Emergency Service'),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='has_lab',
            field=models.BooleanField(default=True, help_text='Lab/ Investigation'),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Closed/ Operating'),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='name',
            field=models.CharField(help_text='Name of Institution', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='phone',
            field=models.CharField(help_text='Contact Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='provides_ambulance',
            field=models.BooleanField(default=True, help_text='Ambulance service'),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='region',
            field=models.CharField(help_text='Region i.e. Province or State', max_length=15),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='tollfree_no',
            field=models.CharField(help_text='Toll Free Number', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalinformation',
            name='type',
            field=models.CharField(help_text='Type of hospital facility i.e. special /general', max_length=4),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='block',
            field=models.CharField(help_text='Building Block Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='department',
            field=models.ForeignKey(help_text='Department Related to', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.departmentinformation'),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='room_type',
            field=models.CharField(help_text='Type i.e. ICU / CCU / General', max_length=4),
        ),
        migrations.AlterField(
            model_name='roominformation',
            name='sub_block',
            field=models.CharField(help_text='Sub Block Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='closure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Apply up till'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='department',
            field=models.ForeignKey(help_text='Department Related To', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.departmentinformation'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='description',
            field=models.CharField(help_text='Vacancy Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital Related To', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.hospitalinformation'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='position',
            field=models.CharField(help_text='Position of vacancy', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='required_experience',
            field=models.IntegerField(default=0, help_text='Experience Required Years'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='total_open',
            field=models.IntegerField(default=1, help_text='Total Vacant Position'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='type',
            field=models.CharField(help_text='Type of Vacancy', max_length=10),
        ),
    ]
