# Generated by Django 3.1.4 on 2021-01-31 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinformation',
            name='depart_head',
            field=models.ForeignKey(help_text='Department Name', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentinformation',
            name='hospital',
            field=models.ForeignKey(help_text='Related Hospital', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.hospitalinformation'),
        ),
        migrations.AddField(
            model_name='bedinformation',
            name='room',
            field=models.ForeignKey(help_text='Room Related To', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.roominformation'),
        ),
        migrations.AddIndex(
            model_name='vacancyinfo',
            index=models.Index(fields=['type', 'position', 'department'], name='vacantpost_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancyinfo',
            index=models.Index(fields=['closure_date'], name='closedt_idx'),
        ),
        migrations.AddIndex(
            model_name='roominformation',
            index=models.Index(fields=['is_active', 'room_type'], name='roomty_idx'),
        ),
        migrations.AddIndex(
            model_name='bedinformation',
            index=models.Index(fields=['is_active', 'is_occupied'], name='available_idx'),
        ),
        migrations.AddIndex(
            model_name='bedinformation',
            index=models.Index(fields=['planned_service_date'], name='service_idx'),
        ),
    ]
