# Generated by Django 3.1.4 on 2021-02-20 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalinfo', '0002_auto_20210131_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinformation',
            name='depart_head',
            field=models.ForeignKey(help_text='Department Head Name', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentinformation',
            name='name',
            field=models.CharField(help_text='Department Name', max_length=4),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='type',
            field=models.CharField(help_text='Type of Vacancy', max_length=4),
        ),
    ]
