# Generated by Django 3.1.4 on 2021-01-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0001_initial'),
        ('medicalofficer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('case_type', models.CharField(max_length=10)),
                ('observation', models.CharField(max_length=500)),
                ('patient_type', models.CharField(max_length=10)),
                ('case_status', models.CharField(max_length=3)),
                ('department', models.CharField(max_length=3)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('observer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicalofficer.medicalofficer')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('referral_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.referral')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('observation', models.CharField(max_length=2500)),
                ('symptoms', models.CharField(max_length=2500)),
                ('allergies', models.CharField(max_length=10)),
                ('is_investigation_req', models.BooleanField(default=False)),
                ('diagnose_date', models.DateTimeField(auto_now_add=True)),
                ('followup_date', models.DateTimeField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casehistory.casehistory')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(max_length=4)),
                ('duration_use', models.IntegerField()),
                ('usage', models.CharField(max_length=100)),
                ('usage_remarks', models.CharField(max_length=500)),
                ('medicine', models.CharField(max_length=30)),
                ('general_name', models.CharField(max_length=10)),
                ('dose', models.IntegerField()),
                ('dose_measure', models.CharField(max_length=5)),
                ('side_effects', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casehistory.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationHistory',
            fields=[
                ('investigation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('planned_date', models.DateTimeField()),
                ('investigation_type', models.CharField(max_length=5)),
                ('investigation_date', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=True)),
                ('pre_remarks', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casehistory.diagnosis')),
                ('permofrmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalofficer.medicalofficer')),
            ],
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['is_active'], name='activemed_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['medicine_type'], name='medtype_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['dose', 'dose_measure'], name='doseage_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationhistory',
            index=models.Index(fields=['investigation_date'], name='invdt_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationhistory',
            index=models.Index(fields=['investigation_type'], name='invty_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['diagnose_date'], name='diagnosedt_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['followup_date'], name='follow_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case_type'], name='casety_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case_status', 'department'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['entered_date'], name='admitdate_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['patient_type'], name='patient_idx'),
        ),
    ]
