# Generated by Django 3.1.4 on 2021-02-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casehistory', '0003_auto_20210131_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='patient_id',
            field=models.ForeignKey(help_text='Patient Username', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
