# Generated by Django 3.1.4 on 2021-01-01 11:22

from django.conf import settings
from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ref_id', models.IntegerField()),
                ('ref_field', models.CharField(max_length=20)),
                ('ref_table', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=50)),
                ('file_ext', models.CharField(max_length=5)),
                ('file', models.FileField(upload_to=filemanager.models.file_path)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(filemanager.models.get_defaultUser), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['ref_id', 'ref_field', 'ref_table'], name='ref_idx'),
        ),
    ]
