# Generated by Django 3.1.4 on 2021-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ref_id', models.IntegerField(help_text='Related Record id')),
                ('ref_field', models.CharField(help_text='Related Field Name', max_length=20)),
                ('ref_table', models.CharField(help_text='Records related to Table', max_length=20)),
                ('file_type', models.CharField(help_text='Type of File eg. XRAY, CT-SCAN', max_length=10)),
                ('file', models.FileField(help_text='attachment files', upload_to='attachment/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
