# Generated by Django 3.1.4 on 2021-01-31 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ref_id', models.IntegerField(help_text='Related Record id')),
                ('ref_field', models.CharField(help_text='Related Field Name', max_length=20)),
                ('ref_table', models.CharField(help_text='Records related to Table', max_length=20)),
                ('file_type', models.CharField(help_text='Type of File eg. XRAY, CT-SCAN', max_length=10)),
                ('file', models.FileField(help_text='attachment files', upload_to='attachment/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['ref_id', 'ref_field', 'ref_table'], name='ref_idx'),
        ),
    ]
