# Generated by Django 3.1.4 on 2021-01-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthmap.medicalofficer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalOfficer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('join_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(on_delete=models.SET(healthmap.medicalofficer.models.get_defaultUser), to=settings.AUTH_USER_MODEL)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patients.staffpersons')),
            ],
        ),
    ]
