# Generated by Django 3.1.4 on 2021-01-31 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalOfficer',
            fields=[
                ('officer_id', models.AutoField(help_text='Officer Id', primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(help_text='MO Position', max_length=20)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(help_text='Related Department', on_delete=django.db.models.deletion.CASCADE, to='hospitalinfo.departmentinformation')),
            ],
        ),
    ]
