# Generated by Django 3.1.4 on 2021-01-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficer', '0002_auto_20210102_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalofficer',
            old_name='entered_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='medicalofficer',
            name='entered_by',
        ),
    ]
