# Generated by Django 3.1.4 on 2021-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficer', '0005_auto_20210202_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalofficer',
            name='position',
            field=models.CharField(help_text='MO Position', max_length=4),
        ),
    ]
