# Generated by Django 3.1.4 on 2021-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFamily',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('relation', models.CharField(max_length=20)),
                ('relation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_billable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffPersons',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_hospital_staff', models.BooleanField(default=False)),
                ('staff_post', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
