# Generated by Django 3.1.4 on 2021-01-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffamily',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='staffpersons',
            name='entered_by',
        ),
    ]
