# Generated by Django 3.1.4 on 2021-02-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_auto_20210131_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafffamily',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Is billable patient'),
        ),
        migrations.AlterField(
            model_name='stafffamily',
            name='relation',
            field=models.CharField(help_text='Relation to Staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='stafffamily',
            name='relation_id',
            field=models.AutoField(help_text='Relationship Id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stafffamily',
            name='staff_id',
            field=models.ForeignKey(help_text='Related Staff Id', on_delete=django.db.models.deletion.CASCADE, to='patients.staffpersons'),
        ),
        migrations.AlterField(
            model_name='stafffamily',
            name='username',
            field=models.ForeignKey(help_text='Username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffpersons',
            name='is_hospital_staff',
            field=models.BooleanField(default=False, help_text='Is hospital Staff or Not'),
        ),
        migrations.AlterField(
            model_name='staffpersons',
            name='staff_post',
            field=models.CharField(help_text='Position of Staff', max_length=25),
        ),
        migrations.AlterField(
            model_name='staffpersons',
            name='username',
            field=models.ForeignKey(help_text='Username of the Staff', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
