# Generated by Django 3.1.4 on 2021-02-06 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(help_text='Additioanl Settings Table Code', max_length=20, null=True)),
                ('code', models.CharField(help_text='Additioanl Settings Unique Code', max_length=10, null=True)),
                ('value', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True, help_text='Enable on Selection')),
                ('modified_date', models.DateField(default=django.utils.timezone.now, help_text='Modified Date')),
            ],
        ),
        migrations.AddIndex(
            model_name='xsettings',
            index=models.Index(fields=['identity', 'code'], name='xinfo_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xsettings',
            unique_together={('identity', 'code')},
        ),
    ]
