# Generated by Django 3.1.4 on 2021-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsettings',
            name='tablespace',
            field=models.CharField(help_text='Table Code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='xsettings',
            name='identity',
            field=models.CharField(help_text='Additioanl Settings Identity Code', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='xsettings',
            unique_together={('tablespace', 'identity', 'code')},
        ),
    ]
