# Generated by Django 3.1.4 on 2021-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20210130_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklist',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration Blocklisted'),
        ),
    ]
