# Generated by Django 3.1.4 on 2021-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20210131_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='source',
            field=models.CharField(choices=[('GEN', 'General'), ('CS', 'Cyber Security'), ('NDS', 'Network Intrusuion')], default='GEN', help_text='Type of Incidence Source', max_length=4),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='type',
            field=models.CharField(choices=[('GEN', 'General'), ('PDEF', 'Pre Defined'), ('NDS', 'Network Intrusuion')], default='GEN', help_text='Type of Block List', max_length=4),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='type',
            field=models.CharField(choices=[('AV', 'Access Violation'), ('ARP', 'ARP Poisioning'), ('MAL', 'Malicious Code'), ('EDP', 'Eves Dropping')], default='AV', help_text='Type of Incidence Reported', max_length=4),
        ),
    ]
