# Generated by Django 3.1.4 on 2021-01-30 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20210130_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklist',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 10, 40, 37, 877529, tzinfo=utc), help_text='Block List active Date'),
        ),
    ]
