# Generated by Django 3.1.4 on 2021-01-30 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_blocklist_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklist',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 10, 46, 21, 332550, tzinfo=utc), help_text='Block List active Date'),
        ),
    ]
