# Generated by Django 3.1.4 on 2021-01-30 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20210130_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklist',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Block List active Date'),
        ),
    ]
