# Generated by Django 3.1.4 on 2021-01-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('thread_title', models.CharField(max_length=1000)),
                ('tags', models.SlugField(max_length=200)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=5000)),
                ('created_by', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forums')),
            ],
            options={
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['tags'], name='tags_idx'),
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['is_closed', 'created_by'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['is_closed', 'created_date'], name='created_idx'),
        ),
    ]
