# Generated by Django 3.1.4 on 2021-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(help_text='User Comment', max_length=5000)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of Comment')),
            ],
            options={
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('thread_title', models.CharField(help_text='Title of Discussion', max_length=1000)),
                ('tags', models.SlugField(help_text='Tags for Search', max_length=200)),
                ('is_closed', models.BooleanField(default=False, help_text='Marked as closed')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of Creation')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Last Update Date')),
            ],
        ),
    ]
