# Generated by Django 3.1.4 on 2021-01-31 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('thread_title', models.CharField(help_text='Title of Discussion', max_length=1000)),
                ('tags', models.SlugField(help_text='Tags for Search', max_length=200)),
                ('is_closed', models.BooleanField(default=False, help_text='Marked as closed')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of Creation')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Last Update Date')),
                ('created_by', models.ForeignKey(help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(help_text='User Comment', max_length=5000)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of Comment')),
                ('created_by', models.ForeignKey(help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('thread_id', models.ForeignKey(help_text='Main Conversation Thread', on_delete=django.db.models.deletion.RESTRICT, to='forums.forums')),
            ],
            options={
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['tags'], name='tags_idx'),
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['is_closed', 'created_by'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='forums',
            index=models.Index(fields=['is_closed', 'created_date'], name='created_idx'),
        ),
    ]
