# Generated by Django 3.1.4 on 2021-01-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_auto_20210103_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(default=None, help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
