# Generated by Django 3.1.4 on 2021-01-09 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0006_auto_20210103_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='thread_id',
            field=models.ForeignKey(help_text='Main Conversation Thread', on_delete=django.db.models.deletion.RESTRICT, to='forums.forums'),
        ),
        migrations.AlterField(
            model_name='forums',
            name='created_by',
            field=models.ForeignKey(help_text='Created By User', on_delete=django.db.models.deletion.CASCADE, to='user.user', to_field='username'),
        ),
    ]
