# Generated by Django 3.1.4 on 2021-01-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
    ]
