# Generated by Django 3.1.4 on 2021-02-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_set', models.CharField(help_text='Menu Sets', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(help_text='Menu', max_length=15, null=True)),
                ('action', models.CharField(help_text='Action Supported', max_length=15, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name')),
            ],
            options={
                'unique_together': {('menu', 'action')},
            },
        ),
    ]
