# Generated by Django 3.1.4 on 2021-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0004_auto_20210220_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('menu_set', models.CharField(help_text='Menu Sets', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('menu', models.CharField(help_text='Menu', max_length=15, null=True)),
                ('action', models.CharField(help_text='Action Supported', max_length=15, null=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'unique_together': {('menu', 'action')},
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
