# Generated by Django 3.1.4 on 2021-01-01 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalofficer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('referral_type', models.CharField(max_length=3)),
                ('refered_from', models.CharField(max_length=50)),
                ('refered_to', models.CharField(max_length=50)),
                ('refered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('refered_remarks', models.CharField(max_length=100)),
                ('refered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalofficer.medicalofficer')),
            ],
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['refered_by'], name='referby_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_type', 'refered_from'], name='from_idx'),
        ),
    ]
