# Generated by Django 3.1.4 on 2021-02-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficer', '0003_auto_20210202_1243'),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='refered_by',
            field=models.ForeignKey(help_text='Referred By', on_delete=django.db.models.deletion.CASCADE, to='medicalofficer.medicalofficer'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='refered_from',
            field=models.CharField(help_text='Refered From ', max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='refered_remarks',
            field=models.CharField(help_text='Refered Remarks', max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='refered_to',
            field=models.CharField(help_text='Refered To', max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_id',
            field=models.AutoField(help_text='Referral Identification Number', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(help_text='Referral Type', max_length=3),
        ),
    ]
